services:
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=josgarlop123
      - MARIADB_DATABASE=ticket-logger-servlet
      - MARIADB_USER=josgarlop
      - MARIADB_PASSWORD=passjosgarlop
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
